### ISSUE TITLE
Request: MC constructor without known subgradients

### ISSUE THREAD

**Issue by kamilkhanlab** [PSORLab/McCormick.jl#63]
Hi all,

It'd be great to have a constructor for `MC` which takes just the `cv`, `cc`, and `Intv` arguments, for situations where we don't know or care about subgradients. This specific constructor would be useful when playing around with e.g. the various McCormick composition rules, and the Scott-Barton relaxations of ODE solutions, and when introducing these concepts to new students. 

Of course we can already "roll our own" constructor based on `MC`'s default constructor, but this requires a user to know what an `SVector` is and how to use it, and to know what a subgradient is. 

Kamil

**Comment by DimitriAlston** [comment]
Thanks for the request, we have added this to the next version of McCormick.jl. Similar to the other constructors where the user doesn't provide subgradients or an indication of the object's dimension, McCormick will set the subgradients equal to 0 by default.
